# ==================================================
# Nova Security - Jekyll Site Configuration
# ==================================================

# Site Settings
# --------------------------------------------------
baseurl: ''
permalink: /:title/
title: 'Nova Security - Secure Your Future, Today'

# Analytics
# --------------------------------------------------
google_analytics_id: ""

# Homepage Configuration
# --------------------------------------------------
homepage:
  show_call_box: true

# Logo Configuration
# --------------------------------------------------
logo:
  main: "../../assets/images/site_logo.webp"
  main_2x: "../../assets/images/site_logo.webp"
  dark: "../../assets/images/site_logo.webp"
  dark_2x: "../../assets/images/site_logo.webp"

# Footer Configuration
# --------------------------------------------------
footer:
  copyright_text: 'You can start and finish one of these popular software landing in under a day - for free! Check the list below'

# SEO Configuration
# --------------------------------------------------
seo:
  meta_og_title: "Nova Security"
  meta_og_type: "website"
  meta_og_url: "https://themeplugs.com"
  meta_og_image: "g"
  meta_og_description: "Nova - Our goal is to pioneer a safe digital landscape through our advanced penetration testing and innovative blockchain security services, empowering businesses to grow with confidence"
  meta_twitter_card: "summary"
  meta_twitter_site: "@nova"
  meta_twitter_creator: "@nova"

# Sass Configuration
# --------------------------------------------------
sass:
  indentWidth: 4
  style: compact # Options: nested, expanded, compact, compressed
  precision: 10
  sass_dir: _sass

# Jekyll Plugins
# --------------------------------------------------
plugins:
  - jekyll-environment-variables
  
gems: ['kramdown']

# Build Configuration
# --------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - vendor
  - Procfile
  - Rakefile

# Archives Configuration
# --------------------------------------------------
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'

# Pagination Configuration
# --------------------------------------------------
paginate: 10
paginate_path: "/page:num/"

# GitHub Pages Configuration
# --------------------------------------------------
# Uncomment and configure for GitHub Pages deployment:
# domain: yourdomain.com      # Force HTTPS domain (without http://)
# url: https://yourdomain.com  # Base hostname and protocol
# baseurl:                    # Subfolder if site is served in a subfolder
